// data = [{
//     "glacialName": "Gangotri Glacier",
//     "glacialLongitude": "79.0831",
//     "glacialLatitude": "30.9010",
//     "glacialRegion": "Uttarakhand, India",
//     "glacialArea": "150",
//     "glacialAffectingArea": ["Bhagirathi River", "Ganges Basin"],
//     "minLakeSize": 0.1,
//     "maxLakeSize": 5.0,
//     "minTemperature": -15,
//     "maxTemperature": 10,
//     "minWindSpeed": 0.5,
//     "maxWindSpeed": 10,
//     "minDamPressure": 0.0,
//     "maxDamPressure": 20.0,
//     "minWaterLevel": 0.1,
//     "maxWaterLevel": 10.0,
//     "minWaterTemperature": -5,
//     "maxWaterTemperature": 5,
//     "minWaterFlowRate": 0.5,
//     "maxWaterFlowrate": 10,
//     "minGroundPressure": 1.0,
//     "maxGroundPressure": 50.0,
//     "minPhValue": 6.5,
//     "maxPhValue": 8.5,
//     "minIceThickness": 5.0,
//     "maxIceThickness": 30.0
//   },
// ];

initData = [
    {
        glacialName: "Gangotri Glacier",
        glacialLongitude: "79.1 N",
        glacialLatitude: "30.9 N",
        glacialRegion: "Uttarkhand",
        glacialArea: "30.2 km",
        glacialAffectingArea:  [
            "Gaumukh",
            "Bhojwasa",
            "Gangotri Town",
            "Harsil Valley",
            "Mukhba Village",
            "Uttarkashi Town",
            "Tehri Dam",
            "Rishikesh",
            "Haridwar"
        ],
        minLakeSize: 1.5,
        maxLakeSize: 2.3,
        minTemperature: -15,
        maxTemperature: 10,
        minWindSpeed:  5,
        maxWindSpeed: 30,
        minDamPressure: 3.5,
        maxDamPressure: 5.2,
        minWaterLevel: 21,
        maxWaterLevel: 27,
        minWaterFlowRate: 200,
        maxWaterFlowRate: 500,
        minGroundPressure: 1.5,
        maxGroundPressure: 3.0,
        minPhValue: 7.0,
        maxPhValue: 8.5,
        minIceThickness: 50,
        maxIceThickness: 540,
    }
]

module.exports = { data: initData };